# Generated by Django 2.2 on 2019-07-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energyaudit', '0004_monthlybill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='power_rating',
            field=models.PositiveIntegerField(choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star'), (6, '6 Star')]),
        ),
    ]
