# Generated by Django 2.2 on 2019-07-20 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energyaudit', '0006_auto_20190719_2247'),
        ('energyaudit', '0005_friend'),
    ]

    operations = [
    ]
