# Generated by Django 2.2 on 2019-07-20 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energyaudit', '0008_friend_current_user'),
        ('energyaudit', '0007_disaggregationresults'),
    ]

    operations = [
    ]
