# Generated by Django 2.2 on 2019-07-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energyaudit', '0009_merge_20190720_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='house_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('villa', 'Villa'), ('bungalow', 'Bungalow')], default='apartment', max_length=60, verbose_name='House Type'),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='power_rating',
            field=models.PositiveIntegerField(choices=[(0, '0 Star'), (1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')]),
        ),
    ]
