# Generated by Django 2.2 on 2019-08-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energyaudit', '0011_auto_20190720_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaggregationresults',
            name='ac',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='disaggregationresults',
            name='fridge',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='disaggregationresults',
            name='total_aggregate',
            field=models.FloatField(default=12346),
        ),
        migrations.AlterField(
            model_name='disaggregationresults',
            name='washing_machine',
            field=models.FloatField(default=0),
        ),
    ]
